version: '3'
services:
  frr1:
    image: crosskicker/frr-image-c:latest           # Utiliser l'image 'frr-image-c'
    container_name: frr1                # Nommer ce conteneur 'frr1'
    privileged: true                    # Nécessaire pour FRRouting
    networks:
      - net-r1-r2                       # Réseau entre frr1 et frr2
    volumes:
      - /etc/frr                        # Volume anonyme monté sur /etc/frr

  frr2:
    image: crosskicker/frr-image-c:latest            # Utiliser l'image 'frr-image-c'
    container_name: frr2                # Nommer ce conteneur 'frr2'
    privileged: true                    # Nécessaire pour FRRouting
    networks:
      - net-r1-r2                       # Réseau entre frr1 et frr2
      - net-r2-r3                       # Réseau entre frr2 et frr3
    volumes:
      - /etc/frr                        # Volume anonyme monté sur /etc/frr

  frr3:
    image: crosskicker/frr-image-c:latest            # Utiliser l'image 'frr-image-c'
    container_name: frr3                # Nommer ce conteneur 'frr3'
    privileged: true                    # Nécessaire pour FRRouting
    networks:
      - net-r2-r3                       # Réseau entre frr2 et frr3
    volumes:
      - /etc/frr                        # Volume anonyme monté sur /etc/frr

# Définir les réseaux
networks:
  net-r1-r2:
    driver: bridge
  net-r2-r3:
    driver: bridge
